name: Program Unit Tests

on:
  workflow_call:
  push:
    branches: [main]
    paths:
      - "program/program/**"
      - "program/Cargo.*"
      - ".github/workflows/program-unit.yml"
  pull_request:
    branches: [main]
    paths:
      - "program/program/**"
      - "program/Cargo.*"
      - ".github/workflows/program-unit.yml"

env:
  CARGO_TERM_COLOR: always
  RUST_LOG: info

permissions:
  contents: read

jobs:
  unit-test:
    name: Unit Tests with Coverage
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: llvm-tools-preview

      - name: Install coverage tools
        run: cargo install cargo-llvm-cov

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
          workspaces: ./program

      - name: Run unit tests with coverage
        run: |
          echo "🧪 Running unit tests with coverage..."
          cd program/program
          cargo llvm-cov --lib --tests --lcov --output-path ../coverage-unit.lcov

      - name: Generate HTML coverage report
        run: |
          cd program/program
          cargo llvm-cov --html --output-dir ../coverage-html-unit

      - name: Display coverage summary
        run: |
          cd program/program
          cargo llvm-cov --summary-only

      - name: Upload coverage reports
        uses: actions/upload-artifact@v4
        with:
          name: unit-coverage-reports
          path: |
            program/coverage-unit.lcov
            program/coverage-html-unit/
          retention-days: 30

      - name: Show failure logs
        if: failure()
        uses: ./.github/actions/show-failure-logs
        with:
          test-type: "Program unit"
