name: Publish SDKs

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      publish_typescript:
        description: "Publish TypeScript SDK to npm"
        type: boolean
        default: true
      publish_rust:
        description: "Publish Rust SDK to crates.io"
        type: boolean
        default: true

permissions:
  contents: read

jobs:
  publish-typescript:
    if: ${{ startsWith(github.ref, 'refs/tags/') || github.event.inputs.publish_typescript == 'true' }}
    runs-on: ubuntu-latest
    environment: npm-publish

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install Shank
        run: cargo install shank-cli

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
          workspaces: ./program

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org"

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10.14.0

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install dependencies
        run: cd program && make install

      - name: Setup Solana CLI
        uses: ./.github/actions/setup-solana

      - name: Build Solana program and generate clients
        run: cd program && make build

      - name: Install TypeScript dependencies
        working-directory: program/clients/typescript
        run: pnpm install --frozen-lockfile

      - name: Build TypeScript SDK
        working-directory: program/clients/typescript
        run: pnpm run build

      - name: Run TypeScript tests
        working-directory: program/clients/typescript
        run: pnpm run test:ci:unit

      - name: Publish to npm
        working-directory: program/clients/typescript
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish-rust:
    if: ${{ startsWith(github.ref, 'refs/tags/') || github.event.inputs.publish_rust == 'true' }}
    runs-on: ubuntu-latest
    environment: crates-publish

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Install Shank
        run: cargo install shank-cli

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
          workspaces: ./program

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10.14.0

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install dependencies
        run: cd program && make install

      - name: Setup Solana CLI
        uses: ./.github/actions/setup-solana

      - name: Build Solana program and generate clients
        run: cd program && make build

      - name: Format Rust code
        working-directory: program/clients/rust
        run: cargo fmt --check

      - name: Lint Rust code
        working-directory: program/clients/rust
        run: cargo clippy -- -D warnings

      - name: Build Rust client
        working-directory: program/clients/rust
        run: cargo build --release

      - name: Run Rust tests
        working-directory: program/clients/rust
        run: cargo test

      - name: Publish to crates.io
        working-directory: program/clients/rust
        run: cargo publish --token ${{ secrets.CRATES_IO_TOKEN }}

  create-release:
    if: startsWith(github.ref, 'refs/tags/') && always() && !cancelled()
    needs: [publish-typescript, publish-rust]
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            ## SDKs Published

            ### TypeScript SDK
            - Package: `@solana-commerce/program-client`
            - Version: ${{ github.ref_name }}
            - Registry: npm

            ### Rust SDK  
            - Package: `commerce-program-client`
            - Version: ${{ github.ref_name }}
            - Registry: crates.io

            ## Installation

            **TypeScript/JavaScript:**
            ```bash
            npm install @solana-commerce/program-client@${{ github.ref_name }}
            ```

            **Rust:**
            ```toml
            [dependencies]
            commerce-program-client = "${{ github.ref_name }}"
            ```
          draft: false
          prerelease: ${{ contains(github.ref_name, '-') }}
